### PR TITLE
Replacing PNG power logo with a more beautiful SVG version

### PR DESCRIPTION
**Pull request by g3n35i5**
After seeing this pixelated accident of a power symbol, I couldn't help but donate a nicer version to this project. The SVG version is even smaller than the PNG, so more space for code! 

Here's a before and after comparison:

new_power_logo

Beautiful, isn't it?

So I donate this code and the SVG under the "WTFPL" license, do whatever you want with it :)

If you need more graphics in the future, don't hesitate to ask me for help before something like this happens again ;)

Many greetings
g3n35i5

### CODE REVIEW

**Review by AiyionPrime — COMMENTED** [review]
Adding several features to a pull request is a nasty habit; consider not adding commits, that have nothing to do with your feature request, the next time you contribute to others projects.

**Review by AiyionPrime — CHANGES_REQUESTED** [review]
The logo looks quite nice, we'll be happy to use it.

For now your PR seems to break the extended page in line 204: https://github.com/freifunkh/IRP-Cannon/blob/e122f4351a24450263f8bc494bc5a6971b75109c/web/extended.html.j2#L204

**Comment by g3n35i5** [comment]
Sorry, forgot about that. Here you go.

**Review by AiyionPrime — APPROVED** [review]
Thanks for the effort!

**Pull request merged**
